# -*- coding: utf-8 -*-
"""# 🤖 Rule-Based Chatbot 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCATgCxDzxBvgQq3eXx9oESYEz8B_ZT9
"""

# 🤖 Rule-Based Chatbot

print("🤖 Chatbot: Hello! I am your AI assistant.")
print("Type 'exit' to end the chat.\n")

while True:
    user = input("You: ").lower()

    # Exit condition
    if user == "exit":
        print("🤖 Chatbot: Goodbye! Have a nice day 😊")
        break

    # Greetings
    elif "hello" in user or "hi" in user:
        print("🤖 Chatbot: Hello! How can I help you?")

    # Asking name
    elif "your name" in user:
        print("🤖 Chatbot: I am a Rule-Based Chatbot created for CodSoft Internship.")

    # Asking about user
    elif "how are you" in user:
        print("🤖 Chatbot: I'm just a program, but I'm doing great! 😊")

    # Help
    elif "help" in user:
        print("🤖 Chatbot: I can answer simple questions like greetings, name, time, etc.")

    # Time
    elif "time" in user:
        import datetime
        now = datetime.datetime.now()
        print("🤖 Chatbot: Current time is:", now.strftime("%H:%M:%S"))

    # Date
    elif "date" in user:
        import datetime
        today = datetime.date.today()
        print("🤖 Chatbot: Today's date is:", today)

    # Weather (dummy response)
    elif "weather" in user:
        print("🤖 Chatbot: I can't fetch live weather, but it's always a good day to code! ☀️")

    # Default response
    else:
        print("🤖 Chatbot: Sorry, I didn't understand that. Can you try something else?")

