# -*- coding: utf-8 -*-
"""IMAGE CAPTIONING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zwry4tIChXHdCtVkGeTOicFIzSd4a7rp
"""

!pip install transformers torch torchvision pillow gradio -q

import torch
import gradio as gr

from PIL import Image
from transformers import VisionEncoderDecoderModel
from transformers import ViTImageProcessor
from transformers import AutoTokenizer

model = VisionEncoderDecoderModel.from_pretrained(
    "nlpconnect/vit-gpt2-image-captioning"
)

processor = ViTImageProcessor.from_pretrained(
    "nlpconnect/vit-gpt2-image-captioning"
)

tokenizer = AutoTokenizer.from_pretrained(
    "nlpconnect/vit-gpt2-image-captioning"
)

device = "cuda" if torch.cuda.is_available() else "cpu"

model.to(device)

def generate_caption(image):

    if image.mode != "RGB":
        image = image.convert("RGB")

    pixel_values = processor(
        images=image,
        return_tensors="pt"
    ).pixel_values.to(device)

    output = model.generate(
        pixel_values,
        max_length=40,
        min_length=10,
        num_beams=5,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95
    )

    caption = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    caption = caption.capitalize()

    return caption

app = gr.Interface(
    fn=generate_caption,
    inputs=gr.Image(type="pil"),
    outputs=gr.Textbox(label="Generated Caption"),
    title="AI Image Captioning",
    description="Upload an image and AI will generate a detailed caption"
)

app.launch()

