# -*- coding: utf-8 -*-
"""TIC-TAC-TOE AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lQTypL50zCG0qRpdhRXT1lwNYZ8N_0n
"""

import math

board = [" " for i in range(9)]

def display():

    print()
    print(" " + board[0] + " | " + board[1] + " | " + board[2])
    print("---+---+---")
    print(" " + board[3] + " | " + board[4] + " | " + board[5])
    print("---+---+---")
    print(" " + board[6] + " | " + board[7] + " | " + board[8])
    print()

def winner(b, p):

    wins = [
        [0,1,2],
        [3,4,5],
        [6,7,8],
        [0,3,6],
        [1,4,7],
        [2,5,8],
        [0,4,8],
        [2,4,6]
    ]

    for w in wins:

        if b[w[0]] == p and b[w[1]] == p and b[w[2]] == p:
            return True

    return False

def draw():
    return " " not in board

def minimax(b, depth, is_max, alpha, beta):

    if winner(b, "O"):
        return 1

    if winner(b, "X"):
        return -1

    if " " not in b:
        return 0

    if is_max:

        best = -100

        for i in range(9):

            if b[i] == " ":

                b[i] = "O"

                score = minimax(b, depth + 1, False, alpha, beta)

                b[i] = " "

                best = max(best, score)

                alpha = max(alpha, best)

                if beta <= alpha:
                    break

        return best

    else:

        best = 100

        for i in range(9):

            if b[i] == " ":

                b[i] = "X"

                score = minimax(b, depth + 1, True, alpha, beta)

                b[i] = " "

                best = min(best, score)

                beta = min(beta, best)

                if beta <= alpha:
                    break

        return best

def ai_move():

    best_score = -100
    move = 0

    for i in range(9):

        if board[i] == " ":

            board[i] = "O"

            score = minimax(board, 0, False, -100, 100)

            board[i] = " "

            if score > best_score:

                best_score = score
                move = i

    board[move] = "O"

print("TIC TAC TOE")
print("You are X")
print("AI is O")

while True:

    display()

    try:
        pos = int(input("Enter position 1-9: ")) - 1

    except:
        print("Enter valid number")
        continue

    if pos < 0 or pos > 8 or board[pos] != " ":
        print("Invalid Move")
        continue

    board[pos] = "X"

    if winner(board, "X"):
        display()
        print("You Win")
        break

    if draw():
        display()
        print("Draw")
        break

    ai_move()

    if winner(board, "O"):
        display()
        print("AI Wins")
        break

    if draw():
        display()
        print("Draw")
        break

